INSERT INTO breeds (breedID, breed, traits, fur_colour, breed_category, origin_country, health_issues)
VALUES
(1,'Labrador Retriever','Loyal friendly intelligent energetic good-natured','Yellow Black Chocolate','Gundog','Canada','Hip dysplasia obesity ear infections'),
(2,'German Shepherd','Loyal intelligent protective confident trainable','Black Tan','Pastoral','Germany','Hip dysplasia elbow dysplasia pancreatitis'),
(3,'Bulldog','Loyal calm gentle brave','White Red','Utility','England','Skin allergies respiratory issues obesity'),
(4,'Poodle','Intelligent active affectionate hypoallergenic','White Black Brown Apricot','Utility','France','Hip dysplasia epilepsy bladder stones'),
(5,'Beagle','Curious friendly energetic good-natured','White Tan Red Lemon','Hound','England','Ear infections hip dysplasia epilepsy'),
(6,'Chihuahua','Loyal energetic confident sensitive','Black Brown Tan White','Toy','Mexico','Dental problems eye issues respiratory issues'),
(7,'Boxer','Loyal energetic intelligent playful protective','Fawn Brindle','Working','Germany','Hip dysplasia cancer heart conditions'),
(8,'Golden Retriever','Intelligent friendly kind loyal good-natured','Golden','Gundog','Scotland','Hip dysplasia cancer skin allergies'),
(9,'Pug','Loyal playful affectionate social charming','Fawn Black','Toy','China','Eye problems respiratory issues obesity'),
(10,'Rottweiler','Loyal protective confident strong','Black Tan','Working','Germany','Hip dysplasia cancer elbow dysplasia'),
(11,'Siberian Husky','Independent energetic intelligent playful strong','Black White','Working','Russia','Hip dysplasia eye problems hereditary myopathy'),
(12,'Dachshund','Loyal energetic playful curious','Black Tan','Hound','Germany','Intervertebral disc disease hip dysplasia diabetes'),
(13,'Shih Tzu','Affectionate playful confident good-natured','Black White Brown','Utility','China','Dental problems respiratory issues eye problems'),
(14,'Bichon Frise','Playful affectionate intelligent social','White','Toy','France','Dental problems eye problems bladder stones'),
(15,'Australian Shepherd','Intelligent energetic loyal trainable','Black Red','Pastoral','Australia','Hip dysplasia eye problems epilepsy'),
(16,'Basset Hound','Affectionate patient gentle good-natured','Black Tan','Hound','France','Dental problems ear infections obesity'),
(17,'Cocker Spaniel','Affectionate intelligent energetic good-natured','Black Brown','Gundog','England','Ear infections hip dysplasia eye problems'),
(18,'French Bulldog','Affectionate playful good-natured','White Black Brindle','Utility','France','Breathing problems eye problems hip dysplasia'),
(19,'Pomeranian','Playful energetic intelligent good-natured','Orange Sable Black','Toy','Germany','Dental problems eye problems obesity'),
(20,'Great Dane','Gentle loyal intelligent good-natured','Black Blue Fawn Harlequin','Working','Germany','Hip dysplasia cancer heart conditions'),
(21,'Mastiff','Loyal gentle protective good-natured','Apricot Fawn','Working','England','Hip dysplasia heart conditions cancer'),
(22,'Newfoundland','Loyal intelligent gentle good-natured','Black Brown Grey','Working','Canada','Hip dysplasia heart conditions cancer'),
(23,'Saint Bernard','Loyal intelligent gentle protective','Red White','Working','Switzerland','Hip dysplasia cancer heart conditions'),
(24,'Old English Sheepdog','Gentle intelligent good-natured protective','Blue Grey','Pastoral','England','Hip dysplasia eye problems skin allergies'),
(25,'Irish Wolfhound','Gentle loyal intelligent good-natured','Grey Red Black','Hound','Ireland','Hip dysplasia heart conditions cancer'),
(26,'Greyhound','Intelligent athletic sensitive good-natured','Black White Brindle','Hound','England','Hip dysplasia eye problems heart conditions'),
(27,'Scottish Deerhound','Gentle intelligent good-natured independent','Blue Grey','Hound','Scotland','Hip dysplasia heart conditions cancer'),
(28,'Great Pyrenees','Loyal intelligent gentle protective','White','Working','France','Hip dysplasia cancer skin allergies'),
(29,'Shar Pei','Independent loyal intelligent good-natured','Cream Fawn','Utility','China','Skin allergies eye problems hip dysplasia'),
(30,'Doberman Pinscher','Loyal energetic intelligent protective','Black Red','Working','Germany','Hip dysplasia heart conditions cancer'),
(31,'Weimaraner','Energetic intelligent good-natured loyal','Silver Grey','Gundog','Germany','Hip dysplasia eye problems cancer'),
(32,'Belgian Malinois','Intelligent energetic loyal protective','Fawn Mahogany','Working','Belgium','Hip dysplasia eye problems skin allergies'),
(33,'Rhodesian Ridgeback','Intelligent athletic loyal good-natured','Light Wheaten','Hound','Rhodesia','Hip dysplasia eye problems cancer'),
(34,'English Setter','Intelligent energetic affectionate good-natured','Black White Liver','Gundog','England','Hip dysplasia eye problems cancer'),
(35,'Pointer','Intelligent energetic good-natured affectionate','Black White Liver','Gundog','England','Hip dysplasia eye problems cancer'),
(36,'Gordon Setter','Intelligent energetic good-natured affectionate','Black Tan','Gundog','Scotland','Hip dysplasia eye problems cancer'),
(37,'Irish Setter','Intelligent energetic good-natured affectionate','Red','Gundog','Ireland','Hip dysplasia eye problems cancer'),
(38,'Papillon','Intelligent energetic affectionate good-natured','White Black Sable Red','Toy','France','Dental problems eye problems bladder stones'),
(39,'Pekingese','Independent intelligent affectionate good-natured','Black White Red','Toy','China','Dental problems respiratory issues eye problems'),
(40,'Toy Poodle','Intelligent active affectionate hypoallergenic','White Black Brown Apricot','Utility','France','Hip dysplasia epilepsy bladder stones'),
(41,'Miniature Poodle','Intelligent active affectionate hypoallergenic','White Black Brown Apricot','Utility','France','Hip dysplasia epilepsy bladder stones'),
(42,'Standard Poodle','Intelligent active affectionate hypoallergenic','White Black Brown Apricot','Utility','France','Hip dysplasia epilepsy bladder stones'),
(43,'Affenpinscher','Intelligent energetic playful good-natured','Black Brown Red','Toy','Germany','Dental problems eye problems skin allergies'),
(44,'Boston Terrier','Intelligent energetic affectionate good-natured','Black White','Utility','United States','Eye problems respiratory issues skin allergies'),
(45,'Brussels Griffon','Intelligent energetic affectionate good-natured','Black Red','Toy','Belgium','Dental problems eye problems respiratory issues'),
(46,'Cairn Terrier','Intelligent energetic playful good-natured','Black Wheaten Red','Terrier','Scotland','Dental problems eye problems skin allergies'),
(47,'Chinese Crested','Intelligent energetic affectionate good-natured','Pink White Black','Toy','China','Dental problems eye problems skin allergies'),
(48,'Miniature Schnauzer','Intelligent energetic playful good-natured','Black Salt & Pepper White','Utility','Germany','Dental problems pancreatitis diabetes'),
(49,'Standard Schnauzer','Intelligent energetic playful good-natured','Black Salt & Pepper','Working','Germany','Dental problems pancreatitis diabetes'),
(50,'West Highland White Terrier','Intelligent energetic playful good-natured','White','Terrier','Scotland','Dental problems skin allergies hip dysplasia'),
(51,'Australian Terrier','Intelligent energetic playful good-natured','Red Black & Tan','Terrier','Australia','Dental problems skin allergies hip dysplasia'),
(52,'Border Terrier','Intelligent energetic playful good-natured','Red Wheaten Black','Terrier','England','Dental problems skin allergies hip dysplasia'),
(53,'Coton de Tulear','Intelligent energetic playful good-natured','White','Utility','Madagascar','Dental problems skin allergies hip dysplasia'),
(54,'English Toy Spaniel','Intelligent energetic playful good-natured','White Blenheim','Toy','England','Dental problems skin allergies hip dysplasia'),
(55,'Australian Stumpy Tail Cattle Dog','Intelligent energetic good-natured loyal','Red Black','Working','Australia','Dental problems eye issues skin allergies'),
(56,'American Eskimo Dog','Intelligent energetic playful good-natured','White','Utility','United States','Dental problems skin allergies hip dysplasia'),
(57,'Australian Cattle Dog','Intelligent energetic playful good-natured','Blue Red','Working','Australia','Dental problems skin allergies hip dysplasia'),
(58,'Basset Hound','Gentle patient good-natured affectionate','Black White Red','Hound','France','Dental problems eye issues skin allergies'),
(59,'Australian Kelpie','Intelligent energetic good-natured loyal','Red Black','Pastoral','Australia','Dental problems eye issues skin allergies'),
(60,'Bloodhound','Loyal intelligent good-natured energetic','Red Black','Hound','England','Dental problems eye issues skin allergies'),
(61,'Border Collie','Intelligent energetic playful good-natured','Black White Red','Pastoral','England','Dental problems eye issues skin allergies'),
(62,'Borzoi','Gentle good-natured loyal intelligent','White Cream Red','Hound','Russia','Dental problems eye issues skin allergies'),
(63,'Bull Terrier','Loyal intelligent good-natured energetic','White Red','Terrier','England','Dental problems eye issues skin allergies'),
(64,'Cane Corso','Loyal intelligent good-natured energetic','Black Red','Working','Italy','Dental problems eye issues skin allergies'),
(65,'Cardigan Welsh Corgi','Intelligent energetic playful good-natured','Red Sable Black','Pastoral','Wales','Dental problems eye issues skin allergies'),
(66,'Chesapeake Bay Retriever','Intelligent energetic playful good-natured','Brown Tan','Gundog','United States','Dental problems eye issues skin allergies'),
(67,'Saluki','Intelligent energetic good-natured loyal','Cream Red','Hound','Middle East','Dental problems eye issues skin allergies'),
(68,'English Setter','Intelligent energetic playful good-natured','Lemon White','Gundog','England','Dental problems eye issues skin allergies'),
(69,'Field Spaniel','Intelligent energetic playful good-natured','Black Liver','Gundog','England','Dental problems eye issues skin allergies'),
(70,'Flat-Coated Retriever','Intelligent energetic playful good-natured','Black Liver','Gundog','England','Dental problems eye issues skin allergies'),
(71,'French Spaniel','Intelligent energetic playful good-natured','Brown White','Gundog','France','Dental problems eye issues skin allergies'),
(72,'German Shorthaired Pointer','Intelligent energetic playful good-natured','Black Liver','Gundog','Germany','Dental problems eye issues skin allergies'),
(73,'German Wirehaired Pointer','Intelligent energetic playful good-natured','Black Liver','Gundog','Germany','Dental problems eye issues skin allergies'),
(74,'Giant Schnauzer','Intelligent energetic loyal good-natured','Black Pepper','Working','Germany','Dental problems eye issues skin allergies'),
(75,'Glen of Imaal Terrier','Intelligent energetic playful good-natured','Blue Red','Terrier','Ireland','Dental problems eye issues skin allergies'),
(76,'Goldendoodle','Intelligent energetic playful good-natured','Golden Cream','Utility','United States','Dental problems eye issues skin allergies'),
(77,'Gordon Setter','Intelligent energetic playful good-natured','Black Tan','Gundog','Scotland','Dental problems eye issues skin allergies'),
(78,'Great Pyrenees','Loyal intelligent gentle protective','White','Giant','France','Dental problems eye issues skin allergies'),
(79,'Harrier','Intelligent energetic playful good-natured','Black White','Hound','England','Dental problems eye issues skin allergies'),
(80,'Hovawart','Loyal intelligent good-natured protective','Black Gold','Working','Germany','Dental problems eye issues skin allergies'),
(81,'Hungarian Puli','Intelligent energetic playful good-natured','Black White','Pastoral','Hungary','Dental problems eye issues skin allergies'),
(82,'Hungarian Vizsla','Intelligent energetic playful good-natured','Rust','Gundog','Hungary','Dental problems eye issues skin allergies'),
(83,'Ibizan Hound','Independent intelligent energetic affectionate','Red White','Hound','Spain','Hip dysplasia eye problems ear infections'),
(84,'Irish Terrier','Lively intelligent independent protective','Red','Terrier','Ireland','Dental problems skin allergies hip dysplasia'),
(85,'Italian Greyhound','Affectionate gentle intelligent playful','Blue Fawn Grey Black','Toy','Italy','Dental problems hip dysplasia patellar luxation'),
(86,'Japanese Chin','Charming affectionate loyal playful','Black White Red','Toy','Japan','Respiratory issues heart problems patellar luxation'),
(87,'Japanese Spitz','Intelligent affectionate playful alert','White','Utility','Japan','Dental problems skin allergies patellar luxation'),
(88,'Kerry Blue Terrier','Confident intelligent loyal affectionate','Blue', 'Terrier', 'Ireland','Dental problems skin allergies hip dysplasia'),
(89,'Komondor','Protective dignified loyal independent','White', 'Working', 'Hungary','Hip dysplasia bloat ear infections'),
(90,'Kuvasz','Loyal patient intelligent protective','White', 'Working','Hungary','Hip dysplasia bloat osteochondritis'),
(91,'Lagotto Romagnolo','Affectionate gentle trainable loyal','Brown White','Utility','Italy','Hip dysplasia cerebellar ataxia storage disease'),
(92,'Leonberger','Friendly gentle affectionate calm','Red Fawn','Working','Germany','Hip dysplasia osteosarcoma bloat'),
(93,'Maltese','Playful affectionate gentle lively','White','Toy','Malta','Dental problems hypoglycemia patellar luxation'),
(94,'Manchester Terrier','Bold intelligent active mischievous','Black Tan','Utility','England','Hip dysplasia patellar luxation von Willebrands disease'),
(95,'Miniature American Shepherd','Intelligent versatile affectionate energetic','Black Blue Red','Pastoral','United States','Hip dysplasia cataracts epilepsy'),
(96,'Miniature Bull Terrier','Playful stubborn courageous loving','White','Utility','England','Heart problems patellar luxation skin allergies'),
(97,'Miniature Pinscher','Fearless energetic alert loyal','Black Tan','Toy','Germany','Hip dysplasia patellar luxation Legg-Calve-Perthes disease'),
(98,'Neapolitan Mastiff','Protective loyal strong powerful','Grey Blue Black Mahogany','Working','Italy','Hip dysplasia cherry eye bloat'),
(99,'Norfolk Terrier','Friendly fearless affectionate independent','Tan Black Red Wheaten','Utility','England','Dental problems patellar luxation heart problems'),
(100,'Norwegian Buhund','Friendly energetic cheerful intelligent','Wheaten Black','Herding','Norway','Hip dysplasia cataracts progressive retinal atrophy'),
(101,'Norwegian Elkhound','Confident loyal bold playful','Black Gray','Nordic','Norway','Hip dysplasia progressive retinal atrophy pyotraumatic dermatitis'),
(102,'Norwich Terrier','Curious affectionate independent lively','Tan Black Red Wheaten','Utility','England','Dental problems patellar luxation mitral valve disease'),
(103,'Nova Scotia Duck Tolling Retriever','Intelligent outgoing affectionate alert','Red Golden','Retriever','Canada','Hip dysplasia progressive retinal atrophy collie eye anomaly'),
(104,'Old English Bulldog','Confident affectionate loving athletic','Brindle Fawn Red White','Working','England','Hip dysplasia respiratory problems cherry eye'),
(105,'Otterhound','Amiable boisterous friendly independent','Black Tan','Hound','England','Hip dysplasia epilepsy gastric torsion'),
(106,'Parson Russell Terrier','Active bold fearless clever friendly','White Tan Black Red Wheaten','Utility','England','Legg-Calve-Perthes disease lens luxation deafness'),
(107,'Pembroke Welsh Corgi','Smart affectionate alert active','Red Sable Black Tri','Pastoral','Wales','Hip dysplasia intervertebral disc disease epilepsy'),
(108,'Peruvian Inca Orchid','Intelligent affectionate lively alert','Various','Utility','Peru','Hip dysplasia patellar luxation progressive retinal atrophy'),
(109,'Polish Lowland Sheepdog','Friendly outgoing clever agile protective','Various','Herding','Poland','Hip dysplasia progressive retinal atrophy epilepsy'),
(110,'Portuguese Podengo','Alert lively independent affectionate','Various','Hound','Portugal','Hip dysplasia luxating patellas epilepsy'),
(111,'Portuguese Water Dog','Smart spirited athletic friendly trainable','Black Brown White','Working','Portugal','Hip dysplasia progressive retinal atrophy storage disease'),
(112,'Pyrenean Mastiff','Gentle protective calm patient','White Grey Tan','Working','Spain','Hip dysplasia elbow dysplasia entropion'),
(113,'Pyrenean Shepherd','Athletic intelligent affectionate lively','Various','Herding','France','Hip dysplasia progressive retinal atrophy patellar luxation'),
(114,'Rat Terrier','Intelligent lively affectionate inquisitive','Various','Toy','United States','Hip dysplasia patellar luxation demodectic mange'),
(115,'Russell Terrier','Friendly fearless intelligent active','Various','Utility','England','Legg-Calve-Perthes disease deafness lens luxation'),
(116,'Schipperke','Alert curious fearless independent','Black','Utility','Belgium','Legg-Calve-Perthes disease hip dysplasia epilepsy'),
(117,'Shetland Sheepdog','Affectionate loyal intelligent lively','Various','Pastoral','Scotland','Hip dysplasia progressive retinal atrophy epilepsy'),
(118,'Shiba Inu','Fox-like alert good-natured confident','Red Sesame Black Tan Cream','Non-Sporting','Japan','Hip dysplasia patellar luxation eye problems'),
(119,'Shih Tzu','Proud affectionate clever friendly','Various','Toy','China','Brachycephalic syndrome hip dysplasia patellar luxation'),
(120,'Silky Terrier','Friendly spunky affectionate confident','Blue Tan','Terrier','Australia','Tracheal collapse elbow dysplasia patellar luxation'),
(121,'Sloughi','Gentle noble aloof sensitive','Various','Hound','Morocco','Hip dysplasia progressive retinal atrophy gastric torsion'),
(122,'Spanish Water Dog','Hard-working rustic intelligent loyal','Various','Working','Spain','Hip dysplasia progressive retinal atrophy cataracts'),
(123,'Spinone Italiano','Gentle sociable patient docile','White Orange Roan Brown Roan','Pointer','Italy','Hip dysplasia cerebellar ataxia progressive retinal atrophy'),
(124,'Staffordshire Bull Terrier','Brave affectionate tenacious','Various','Terrier','England','Hip dysplasia cataracts luxating patellas'),
(125,'Sussex Spaniel','Friendly cheerful affectionate sociable','Golden Liver','Terrier','England','Hip dysplasia elbow dysplasia hypothyroidism'),
(126,'Swedish Vallhund','Friendly energetic intelligent sociable','Various','Herding','Sweden','Hip dysplasia progressive retinal atrophy patellar luxation'),
(127,'Tibetan Mastiff','Protective strong reserved gentle','Black Black & Tan Blue Gray','Working','Tibet','Hip dysplasia elbow dysplasia entropion'),
(128,'Tibetan Spaniel','Clever confident assertive affectionate','Various','Toy','Tibet','Brachycephalic syndrome hip dysplasia patellar luxation'),
(129,'Tibetan Terrier','Smart friendly adaptable affectionate','Various','Non-Sporting','Tibet','Hip dysplasia lens luxation progressive retinal atrophy'),
(130,'Toy Fox Terrier','Smart bold playful mischievous','White Tan Black','Toy','United States','Patellar luxation Legg-Calve-Perthes disease'),
(131,'Treeing Walker Coonhound','Smart brave friendly sociable','Various','Hound','United States','Hip dysplasia ear infections hypothyroidism'),
(132,'Vizsla','Loyal affectionate gentle energetic','Rust','Pointer','Hungary','Hip dysplasia epilepsy lymphosarcoma'),
(133,'Weimaraner','Loyal smart fearless alert obedient','Various','Gundog','Germany','Hip dysplasia bloat hypertrophic osteodystrophy'),
(134,'Welsh Springer Spaniel','Friendly cheerful affectionate happy','Red White','Gundog','Wales','Hip dysplasia epilepsy entropion'),
(135,'West Highland White Terrier','Curious happy friendly lively','White','Terrier','Scotland','Atopic dermatitis hip dysplasia luxating patellas'),
(136,'Whippet','Gentle affectionate friendly playful','Various','Hound','England','Hypothyroidism von Willebrands disease eye problems'),
(137,'Wire Fox Terrier','Friendly brave alert playful','White Tan','Toy','England','Hip dysplasia deafness cataracts'),
(138,'Wirehaired Pointing Griffon','Smart friendly trainable gentle','Various','Pointer','Netherlands','Hip dysplasia epilepsy thyroid issues'),
(139,'Wirehaired Vizsla','Loyal gentle affectionate intelligent','Golden Rust','Pointer','Hungary','Hip dysplasia epilepsy cerebellar ataxia'),
(140,'Xoloitzcuintli','Alert calm loyal attentive','Black Gray Liver','Non-Sporting','Mexico','Hip dysplasia patellar luxation skin issues'),
(141,'Yorkshire Terrier','Bold intelligent confident affectionate','Blue Tan','Toy','Australia','Portosystemic shunt patellar luxation tracheal collapse');

